### PR TITLE
Removed getMock method and added class constants

### PR DESCRIPTION
**Pull request by MarioBlazek**
This PR resolves:
* removed deprecated `getMock` method
* tests updated with class constants
* fixed minor typos (buildVioloation -> buildViolation)

### CODE REVIEW

**Comment by MarioBlazek** [comment]
@adamwojs is it actually necessary ? The whole PR will be squashed on merge, right ?

**Comment by adamwojs** [comment]
@MarioBlazek No, it isn't necessary. This is only note for the future 😉

**Comment by andrerom** [comment]
I missed the `UniqueLanguageCodeValidatorTest` addition on first look, what is it for? And seems like a separate concern so should ideally be separate commit, or if a good enough reason for it a separate commit and we'll create merge commit instead of squash*.

\* _This is why @adamwojs suggested separate commit, we don't always squash, if there are several authors or several topics handled in a PR we create merge commit_

**Comment by MarioBlazek** [comment]
@adamwojs @andrerom should I add `UniqueLanguageCodeValidatorTest` to separate commit ?

**Comment by andrerom** [comment]
> should I add UniqueLanguageCodeValidatorTest to separate commit ?

either own PR, or rebase this to have two commits (one for getMock and the rest, and one for adding new tests for UniqueLanguageCodeValidatorTest)

**Comment by MarioBlazek** [comment]
@andrerom created #157 and removed `UniqueLanguageCodeValidatorTest` from this PR

**Comment by andrerom** [comment]
Thanks :)

**Pull request merged**
