### PR TITLE
Library test updated with phpunit compatibility layer

### PR DESCRIPTION
**Pull request by MarioBlazek**
Old `PHPUnit_Framework_TestCase` replaced with new namespaced `PHPUnit\Framework\TestCase`.

### CODE REVIEW

**Comment by MarioBlazek** [comment]
@bdunogier this is just forward compatibility layer. PHPUnit 6 uses non-namespaced classes.

**Comment by andrerom** [comment]
>  PHPUnit 6 uses non-namespaced classes.

-`non-` ? :)

**Comment by MarioBlazek** [comment]
Sorry, `namespaced`. :)

**Comment by andrerom** [comment]
Btw, you'll need to bump phpunit requirement a bit more now ;)
can probably just as well say ^5.7

**Comment by MarioBlazek** [comment]
@andrerom phpunit requirement updated.

**Comment by andrerom** [comment]
@MarioBlazek Seems the composer constraints does not pass anymore, so it fails the phpunit tests

**Comment by MarioBlazek** [comment]
Updated, bumped `matthiasnoback/symfony-dependency-injection-test` version to `~1.0`.

**Pull request merged**
