### PR TITLE
EZP-28224: Setup and fix behat tests on repository-forms:2.0

### PR DESCRIPTION
**Pull request by webhdx**
> JIRA: https://jira.ez.no/browse/EZP-28224

# Description
This PR fixes behat tests and introduces initial configuration for CI to run tests on eZ Platform 2.0.

### CODE REVIEW

**Comment by andrerom** [comment]
Should it pass before review is requested? or is that not expected at this stage?

**Comment by webhdx** [comment]
Sorry due to tremendous amount of work I had no chance to finish this one. @alongosz will continue on this topic.

**Comment by alongosz** [comment]
Please be aware of similar work done in ezpublish-kernel#2166 [with changes in meta-repository](https://github.com/ezsystems/ezplatform/compare/2.0...2.0-fix-behat) (no PR yet). 
I'd prefer to adjust this PR to meta-repository changes once we'll get kernel to work with that.

**Comment by andrerom** [comment]
@webhdx Can you maybe rebase this?

**Comment by webhdx** [comment]
Hey @andrerom I'm on it :)

**Pull request merged**
