### PR TITLE
Fix EZP-25339: Default value length should be between min and max string length

### PR DESCRIPTION
**Pull request by crevillo**
Fixes https://jira.ez.no/browse/EZP-25339

This a requirement to https://github.com/ezsystems/ezpublish-kernel/pull/1574

ping @bdunogier @andrerom

### CODE REVIEW

**Comment by yannickroger** [comment]
you can also ping @glye :)

**Comment by glye** [comment]
+1

**Comment by bdunogier** [comment]
+1

**Comment by andrerom** [comment]
@crevillo ?

**Comment by crevillo** [comment]
wops, didn't see @bdunogier's comment. good question. i also thought about this. i see your point, but if you don't check that property against the StringLengthValidator, how do you check it? I mean, yes, it's a setting, but the strlen of that setting should be between min and max length, shouldn't it?

**Comment by andrerom** [comment]
>  I mean, yes, it's a setting, but the strlen of that setting should be between min and max length, shouldn't it?

It should, but this is not what `property_path ` does afaik: http://symfony.com/doc/current/reference/forms/types/form.html#property-path

property path is afaik wrong here, as the name maps perfectly  to the property it represents: `->defaultValue`.

Checking it against min and max seem to have to be done using something else.

**Comment by glye** [comment]
Agree that defaultValue isn't validator configuration, but a field setting. As for how to check it then, it seems that `FieldDefinitionDefaultValueValidator` exists for this purpose...? (Unsure how to implement it though.)

**Comment by crevillo** [comment]
yep, it's a field setting, but we won't allow the length of this field setting be out of min - max field settings, right? 

Question is... how can i get the posted defaultValue inside https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/FieldType/TextLine/Type.php#L48? 

Actually, what i noticed about this issue (without this patch) is the following. If you set
 * minLength 2
 * maxLength 6
 * defaultValue 'eZ Platform'

validation passed ok. but after, if you add another field, no matter which type is, then it says that defaultValue can't be greater than the maxLength...

here is the screencast. https://youtu.be/VNG54qmL3yQ

So, why that validation doesn't act at first but seems to act after?

**Comment by glye** [comment]
Correct me if I'm wrong, but I think you're not supposed to validate the defaultValue inside validateValidatorConfiguration(), because it isn't part of the validator. It should be done in validateFieldSettings(). So then the question is, how to read the min/max values from there? :)

**Comment by andrerom** [comment]
Guys, afaik this is not a field setting, it is default value, which is a native property on FieldDefintion.

*I'm assuming we are talking about the default value for the field, as set on field definition, not the default value of max/min for field defintion, as set on $validatorConfigurationSchema.*

And afaik there is nothing around to validate it, if it was a field setting it would most likely have been `validateFieldSettings`.

**Comment by crevillo** [comment]
@gyle agree. the reason of trying to solve it in validateValidatorConfiguration is because i can read those min/max values there :). But i was not really convinced that this was the best way to go.

so, any other ideas?

**Comment by crevillo** [comment]
closing as this is not the way to go.

**Comment by glye** [comment]
Sorry, I don't know. If it isn't a field setting, and the api doesn't support default value validation, then it requires some more thought. (But FieldDefinitionDefaultValueValidator sounds like it was intended for this purpose, at least.)

**Comment by andrerom** [comment]
> (But FieldDefinitionDefaultValueValidator sounds like it was intended for this purpose, at least.)

So that is `EzSystems\RepositoryForms\Validator\Constraints\FieldDefinitionDefaultValueValidator`, indeed, looks relevant.

**Comment by andrerom** [comment]
But it uses `$fieldType->validateValue($fieldDefinition, $fieldValue)` which I can't find anywhere.

**Comment by emodric** [comment]
It is in `eZ\Publish\API\Repository\FieldType`

**Comment by andrerom** [comment]
> It is in eZ\Publish\API\Repository\FieldType

right you are, I was grepping on older checkout :sweat_smile: 

ok, that is the way then @crevillo, it basically inits a field value with the default value on it underneath, so everything gets validated.

**Comment by crevillo** [comment]
That's the reason why that validation does not act at first, then?

**Comment by crevillo** [comment]
i'm still stumble on this. afaik, when you add the textLine type, as you guys said, ```FieldDefinitionDefaultValueValidator``` enters the game. And finally it reach Type Validate function https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/FieldType/TextLine/Type.php#L80

But looks like at this very first time, ```$constraints``` values are still not set, and hence, the validation returns correct. So, it looks like this validate function that indeed checks the entered defaultValue is called before $constraints minString and maxLenght are set... 

so, any ideas on how to follow from this? @andrerom, @glye, @pspanja

**Comment by glye** [comment]
> But looks like at this very first time, $constraints values are still not set

If you're sure about this, then it seems bigger changes are needed. Hard to suggest anything without digging deeply into it. The first thing I would look into is changing the order of FieldDefinitionDefaultValueValidator and min/max constraints setup, obviously. Any ideas, @bdunogier?

**Comment by crevillo** [comment]
Well, not entirely sure but seems so if you look at the screencast i added https://youtu.be/VNG54qmL3yQ
doing some debug, looks when validate is performed at first constraints is an array with empty minStringLenght and empty maxStringLength.  That's why validate doesn't return errors there. But if you add any other field, then those constraints values are filled in that validate function and hence, the check is performed...

**Pull request closed without merging**
