### PR TITLE
Fix EZP-24713: Policy limitations edition

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24713

Works on the same principe as FieldDefinitions. Each limitation type needs a form mapper.
Base implementation includes a mapper for SiteAccessLimitationType

## TODO
* [x] Template mechanism
* [x] SiteAccessLimitationMapper
* [x] ContentTypeLimitationMapper
* [x] SectionLimitationMapper
* [x] Tests

### CODE REVIEW

**Comment by andrerom** [comment]
cool

> Each limitation type needs a form mapper.

Could you expand a bit on that? Makes kind of sense as we have similar things for Field Types in Content Types *(and probably Content)*.

**Comment by lolautruche** [comment]
@andrerom Well, each limitation type needs a form to be properly edited. Most can just rely on the `MultipleSelectionBasedMapper`, but it is still needed to provide valid selectable values.

**Comment by lolautruche** [comment]
Now ready for review
Ping @andrerom @bdunogier @pspanja @glye

**Comment by andrerom** [comment]
+1

**Comment by glye** [comment]
+1 afaict

**Pull request merged**
