### PR TITLE
Fix EZP-24382: As a RepositoryForms user I want to delete a FieldDefinition from a ContentType

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24382

Based on #14

### CODE REVIEW

**Comment by lolautruche** [comment]
Review ping @andrerom @bdunogier @yannickroger @dpobel @pspanja

**Comment by lolautruche** [comment]
Also ping @glye

**Comment by andrerom** [comment]
+1

**Comment by pspanja** [comment]
+1

**Comment by glye** [comment]
Late +1

**Pull request merged**
