### PR TITLE
Fix EZP-24442: Implement FieldDefinition form mapper for ezimage

### PR DESCRIPTION
**Pull request by glye**
Manual testing. Is about the same as for ezbinaryfile.

Depends on https://github.com/ezsystems/ezpublish-kernel/pull/1291

https://jira.ez.no/browse/EZP-24442

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by glye** [comment]
Rebased on master.

**Comment by glye** [comment]
Changed translation: Max file size is in bytes, not MB.

**Comment by glye** [comment]
Rebased on master.

**Comment by glye** [comment]
Review ping @lolautruche @pspanja @bdunogier

**Comment by lolautruche** [comment]
+1

**Pull request merged**
