### PR TITLE
Fix EZP-25092: "Allowed content types" selected item, from ezobjectre…

### PR DESCRIPTION
**Pull request by glye**
…lationlist, changes under certain conditions

> Fixes https://jira.ez.no/browse/EZP-25092
> Status: Ready for review

Used wrong sort function, which messed with my array keys. D'oh!

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by bdunogier** [comment]
+1

**Comment by bdunogier** [comment]
Merged, remember to update the PR please.

**Comment by glye** [comment]
Done, thanks.

**Pull request merged**
