### PR TITLE
Fix EZP-24380: Move section form management from PlatformUI to RepositoryForms

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24380

Part of https://github.com/ezsystems/PlatformUIBundle/pull/288

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by lolautruche** [comment]
It's still WIP

**Comment by andrerom** [comment]
Then say so :P

**Comment by andrerom** [comment]
Sorry, should have opened another branch for this, needed master to test https://github.com/ezsystems/PlatformUIBundle/pull/307

It works *(well section/list is broken, but got it to work by entering url manually)*, so feel free to remove my commit here / rebase.

**Comment by lolautruche** [comment]
Now ready for review

@andrerom @bdunogier @yannickroger @glye @pspanja

**Comment by andrerom** [comment]
+1

**Comment by glye** [comment]
+1

**Comment by lolautruche** [comment]
OK now finished, adding `SectionDeleteType` for section deletion using a form

**Pull request merged**
