### PR TITLE
[WIP] Bootstrap 4 support

### PR DESCRIPTION
**Pull request by dew326**
**Jira ticket:** https://jira.ez.no/browse/EZP-27898

# TODO:
- [ ] Behat tests

### CODE REVIEW

**Comment by andrerom** [comment]
I guess this would be for v2 only?

**Comment by alongosz** [comment]
> I guess this would be for v2 only?

Yes. Mostly question to @webhdx - is this BC with eZ Platform v1? If not then maybe we should consider releasing `repository-forms` `v2.0` and targeting this to `2.0` branch.

BTW. The bundle linked in the description should be available on `ezsystems` later today.

**Comment by andrerom** [comment]
> Yes. Mostly question to @webhdx - is this BC with eZ Platform v1? If not then maybe we should consider releasing repository-forms v2.0 and targeting this to 2.0 branch.

well if we release or not is not that important until we do official alpha/beta, but 2.0 branch which stays ahead of master somewhat like we do on kernel would be the way to solve it.

**Comment by webhdx** [comment]
@andrerom @alongosz Yes and no. Content editing hasn't been used yet. In v1, repository-forms is only used for content types, policies, roles, languages etc. This PR doesn't change how these forms are rendered.

Technically it's a BC break as it changes HTML markup for content editing, assuming there are people who are already using unfinished content editing. I will create `2.0` branch, we will have more flexibility in changing more stuff to play along with eZ Platform v2 nicely.

**Comment by webhdx** [comment]
@andrerom @alongosz Yes and no. Content editing hasn't been used yet. In v1, repository-forms is only used for content types, policies, roles, languages etc. This PR doesn't change how these forms are rendered.

I'm not sure how we look at it. Changing HTML markup feels like a BC break, i.e. some people might've already styled their forms using our CSS class names. This is still a big stretch as content editing is unfinished and it's hard to assume anyone is using it in the state it is right now. 

On the other hand we already did a BC break merging templating changes for HybridUI in many recent PRs. @andrerom how should we approach another change?

**Comment by andrerom** [comment]
> In v1, repository-forms is only used for content types, policies, roles, languages etc. 

there is also content create, aka UGC, which would benefit from the work on adding more field types.

I'm unsure if html structure can be considered a BC break or not, it would need to be documented yes, but I'll leave it up to @lserwatka to decide if master should simply be aliased to 2.0.x-dev to signify we have BC breaks, or if we can release these changes to 1.12 also.

**Comment by lserwatka** [comment]
@dew326 could you rebase here?

**Comment by bdunogier** [comment]
I'd indeed expect this to be part of a v2. It doesn't cost much, and prevents any backward compatibility issue.

**Comment by lserwatka** [comment]
I confirm, this will be part of v2 @bdunogier, @alongosz

**Comment by bdunogier** [comment]
> I confirm, this will be part of v2 @bdunogier, @alongosz

Perfect, thanks :)

**Comment by lserwatka** [comment]
Closing in favour of https://github.com/ezsystems/repository-forms/pull/163

**Pull request closed without merging**
