### PR TITLE
EZP-28226: User can't add more fields after removing several of them

### PR DESCRIPTION
**Pull request by webhdx**
> JIRA: https://jira.ez.no/browse/EZP-28226

# Description
This PR fixes Content Type Edit > Add Field Definition action which had been failing if first field definitions were removed. It was caused by assigning already existing identifier. I created a method which resolves new name making sure it doesn't exist in edited Content Type.

# Remarks
It has to be ported upwards to 1.10 and master.

### CODE REVIEW

**Comment by micszo** [comment]
Cannot reload cache on v2 with this branch:
screen shot 2017-12-12 at 16 12 37

**Comment by webhdx** [comment]
@micszo This needs to be rebased on master in order to work in v2. Please test on 1.7 first.

**Comment by micszo** [comment]
Retest OK with eZ Platform EE v1.7.
Moving on to v1.13.

**Comment by micszo** [comment]
Retest OK with eZ Platform EE v1.13.0-beta1 with this branch.

**Comment by micszo** [comment]
@webhdx is it possible to test with v2 before merge?

**Comment by webhdx** [comment]
@micszo It is. https://patch-diff.githubusercontent.com/raw/ezsystems/repository-forms/pull/187.patch

**Comment by micszo** [comment]
Retest OK with eZ Platform EE v2 with patch.

**Comment by lserwatka** [comment]
@webhdx could you merge this up?

**Comment by webhdx** [comment]
@lserwatka Done.

**Comment by andrerom** [comment]
@webhdx This one breaks unit test:
```
There was 1 failure:

1) EzSystems\RepositoryForms\Tests\Form\Processor\ContentTypeFormProcessorTest::testAddFieldDefinition
Expectation failed for method name is equal to <string:addFieldDefinition> when invoked 1 time(s)
Parameter 1 for invocation eZ\Publish\API\Repository\ContentTypeService::addFieldDefinition(eZ\Publish\Core\Repository\Values\ContentType\ContentTypeDraft Object (...), eZ\Publish\API\Repository\Values\ContentType\FieldDefinitionCreateStruct Object (...)) does not match expected value.
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 eZ\Publish\API\Repository\Values\ContentType\FieldDefinitionCreateStruct Object (
     'fieldTypeIdentifier' => 'ezstring'
-    'identifier' => 'new_ezstring_3'
+    'identifier' => 'new_ezstring_1'
     'names' => Array (...)
     'descriptions' => null
     'fieldGroup' => 'content'
     'position' => 1
     'isTranslatable' => null
     'isRequired' => null
     'isInfoCollector' => null
     'validatorConfiguration' => null
     'fieldSettings' => null
     'defaultValue' => null
     'isSearchable' => null
 )

/repository-forms/lib/Form/Processor/ContentTypeFormProcessor.php:119
/repository-forms/tests/RepositoryForms/Form/Processor/ContentTypeFormProcessorTest.php:159
```

**Comment by andrerom** [comment]
And here on 1.5 it break PHP parsing:
```
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /home/travis/build/ezsystems/repository-forms/lib/Form/Processor/ContentTypeFormProcessor.php on line 172
```

**Pull request merged**
