### PR TITLE
Fix EZP-24700: Role assignment CRUD

### PR DESCRIPTION
**Pull request by glye**
Adds role assignment delete form. Required by https://github.com/ezsystems/PlatformUIBundle/pull/344

https://jira.ez.no/browse/EZP-24700

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by glye** [comment]
Tiny review ping @dpobel @yannickroger @lolautruche @pspanja

**Comment by pspanja** [comment]
+1

**Comment by lolautruche** [comment]
+1

**Comment by glye** [comment]
Rebased on master after policy edit commit.

**Pull request merged**
